routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\PostsController;
use App\Http\Controllers\UsersPostsController;
use App\Http\Controllers\CategoriesPostsController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('posts', PostsController::class);
Route::resource('users', UsersPostsController::class);
Route::resource('users.posts', UsersPostsController::class);
Route::resource('categories.posts', CategoriesPostsController::class);

app/Models/Posts.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Posts extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CategoriesPostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CategoriesPostsController extends Controller
{
    public function show($category, $post_id)
    {
        return 'hello world for the categories and the post';
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Posts;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;


class PostsController extends Controller
{
    public function index()
    {
        //get all posts, sorted by newest creation date
        $posts = Posts::orderBy('posts.created_at', 'desc')
            ->join('users', 'users.id', '=', 'posts.author_id')
            ->select('posts.id','posts.title','posts.abstract','posts.body','posts.created_at','posts.updated_at','users.name','users.user')
            ->where('posts.published', true)
            ->get();

        //return to view
        return view('posts.index', ['posts' => $posts]);

    }

    public function show($id)
    {
        //find one post by id
        $posts = Posts::join('users', 'users.id', '=', 'posts.author_id')
            ->select('posts.id','posts.title','posts.abstract','posts.body','posts.created_at','posts.updated_at','users.name','users.user')
            ->where('posts.published', true)
            ->find($id);

        //return to view
        return view('posts.single', ['posts'=> $posts]);
    }

    public function create()
    {
        return view('posts.create');
    }

    public function store(Request $request)
    {

        // validation
        $this->validate($request, [
            'author_id' => 'required|numeric',
            'title'     => 'required',
            'slug'      => 'required',
            'abstract'  => 'required',
            'body'      => 'required'
         ]);

        $input = $request->all();

        DB::insert('insert into posts (author_id, title, slug, abstract, body, published, created_at, updated_at) values (?, ?, ?, ?, ?, ?, NOW(), NOW())',
                   [$input['author_id'],$input['title'],$input['slug'],$input['abstract'],$input['body'],$input['published'] == 'on'? true : false]);
        // redirect
        return redirect('/posts');

    }

    public function update($id, Request $request)
    {
        // Upon update, update the timestamp
        $post = Posts::where('id', $id)
            ->update(['updated_at' => NOW()]);

        return redirect('/posts');
    }

    public function destroy($id)
    {
        //find one post by id then delete
        $post = DB::table('posts')->where('id', $id);
        $post->delete();

        return redirect('/posts');
    }
}

app/Http/Controllers/UsersPostsController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Posts;
use Illuminate\Http\Request;

class UsersPostsController extends Controller
{

    public function index()
    {
        abort(404);
    }

    public function show(Request $request)
    {

        $path = explode('/',$request->path());

        if( count($path) == 2 )
        {
            //find all posts by user
            $posts = Posts::orderBy('posts.created_at', 'desc')
                ->join('users', 'users.id', '=', 'posts.author_id')
                ->select('posts.id','posts.title','posts.abstract','posts.body','posts.created_at','posts.updated_at','users.name','users.user')
                ->where('posts.published', true)
                ->where('users.user', $path[1])
                ->get();

            //return to view
            return view('posts.index', ['posts'=> $posts]);
        } 
        elseif(count($path) == 4)
        {
            //find one post by user and id
            $posts = Posts::join('users', 'users.id', '=', 'posts.author_id')
                ->select('posts.id','posts.title','posts.abstract','posts.body','posts.created_at','posts.updated_at','users.name','users.user')
                ->where('posts.published', true)
                ->where('users.user', $path[1])
                ->find($path[3]);

            if(is_null($posts))
            {
                abort(404);
            }

            return view('posts.single', ['posts'=> $posts]);
        }
        else
        {
            abort(404);
        }
    }
}

resources/views/main.blade.php
<html>
    <head>
        <title>@yield('title')</title>
    </head>
    <body>
        <div class="container">
            @yield('content')
        </div>
    </body>
</html>

resources/views/posts/create.blade.php
@extends('main')

@section('content')

    <form action="{{ route('posts.store') }}" method="POST">
        @csrf
        <label for="author_id">Author ID</label>
        <input id="author_id" name="author_id" type="text" class="@error('author_id') is-invalid @enderror"><br>

        <label for="title">Title</label>
        <input id="title" name="title" type="text" class="@error('title') is-invalid @enderror"><br>

        <label for="slug">Slug</label>
        <input id="slug" name="slug" type="text" class="@error('slug') is-invalid @enderror"><br>

        <label for="abstract">Abstract</label>
        <input id="abstract" name="abstract" type="text" class="@error('abstract') is-invalid @enderror"><br>

        <label for="body">Body</label>
        <textarea id="body" name="body" class="@error('body') is-invalid @enderror" cols="60" rows="10"></textarea><br>

        <label for="published">Published</label>
        <input id="published" name="published" type="checkbox" checked class="@error('published') is-invalid @enderror"><br>

        <button type="submit" class="btn btn-primary">Create</button>
    </form>

@endsection

resources/views/posts/index.blade.php
@extends('main')

@section('content')

    @foreach ($posts as $post)
    <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

            <h1 class="mt-4"><a href="{{ route('posts.show',$post->id) }}">{{$post->title}}</a></h1>

            <!-- Author -->
            <p class="lead">
                by
                <a href="/users/{{ $post->user }}">{{$post->name}}</a>
            </p>

            <hr>

            <!-- Date/Time -->
            <p>Posted on {{$post->created_at}}</p>

            <hr>

            <!-- Post Content -->
            {!! $post->body !!}
            <hr>

            <!-- Special -->
            <a href="{{ route('posts.create')}}">Create New Post</a>


        </div>

    </div>
    @endforeach

@endsection

resources/views/posts/single.blade.php
@extends('main')

@section('content')

    <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

            <h1 class="mt-4"><a href="{{ route('posts.show',$posts->id) }}">{{$posts->title}}</a></h1>

            <!-- Author -->
            <p class="lead">
                by
                <a href="/users/{{$posts->user}}">{{$posts->name}}</a>
            </p>

            <hr>

            <!-- Date/Time -->
            <p>Posted on {{$posts->created_at}} and updated at {{$posts->updated_at}}</p>

            <hr>

            <!-- Post Content -->
            {!! $posts->body !!}
            <hr>

            <!-- Specials -->
            <form action="{{ route('posts.update', $posts->id) }}" method="POST">
                @csrf
                @method('PUT')
                <input type="hidden" name="updated_at" value="now()" />
                <button type="submit" class="btn btn-danger">Update</button>
            </form>
            <form action="{{ route('posts.destroy', $posts->id) }}" method="POST">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>

        </div>

    </div>

@endsection